proxy-providers:
  AKUN_INDONESIA:
    type: file
    path: "./AKUN_INDONESIA.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 30
  AKUN_SINGAPURA:
    type: file
    path: "./AKUN_SINGAPURA.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 30
proxy-groups:
- name: 🟡 BROWSING 🟡
  type: select
  disable-udp: false
  proxies:
  - 🟨 BEST PING 🟨
  - 🟧 LOADBALANCING 🟧
  - 🟩 FALLBACK 🟩
  - ✅ PILIHAN ✅
  url: http://www.gstatic.com/generate_204
  interval: '10'
- name: 🟠 STREAMING 🟠
  type: select
  disable-udp: false
  proxies:
  - 🟨 BEST PING 🟨
  - 🟧 LOADBALANCING 🟧
  - 🟩 FALLBACK 🟩
  - ✅ PILIHAN ✅  
  url: http://www.gstatic.com/generate_204
  interval: '10'
- name: 🟢 SOSMED 🟢
  type: select
  disable-udp: false
  proxies:
  - 🟨 BEST PING 🟨
  - 🟧 LOADBALANCING 🟧
  - 🟩 FALLBACK 🟩
  - 🇮🇩 TRAFFIC INDO 🇮🇩
  url: http://www.gstatic.com/generate_204
  interval: '10' 
- name: 🇮🇩 TRAFFIC INDO 🇮🇩
  type: fallback
  disable-udp: false
  use:
  - AKUN_INDONESIA
  url: http://www.gstatic.com/generate_204
  interval: '10'
 name: 🟨 BEST PING 🟨
  type: url-test
  disable-udp: false
  use:
  - AKUN_INDONESIA
  - AKUN_SINGAPURA
  url: http://www.gstatic.com/generate_204
  interval: '10'
  tolerance: '5'
- name: 🟧 LOADBALANCING 🟧
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN_INDONESIA
  - AKUN_SINGAPURA
  url: http://www.gstatic.com/generate_204
  interval: '360'
- name: 🟩 FALLBACK 🟩
  type: fallback
  disable-udp: false
  use:
  - AKUN_INDONESIA
  - AKUN_SINGAPURA
  url: http://www.gstatic.com/generate_204
  interval: '10'  
- name: ✅ PILIHAN ✅
  type: select
  disable-udp: false
  use:
  - AKUN_INDONESIA
  - AKUN_SINGAPURA
  url: http://www.gstatic.com/generate_204
  interval: '10'  
- name: ⛔ ADBLOCK ⛔
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - 🟨 BEST PING 🟨
  - 🟧 LOADBALANCING 🟧
  - 🟩 FALLBACK 🟩
  - ✅ PILIHAN ✅
  url: http://www.gstatic.com/generate_204
  interval: '10'
- name: 🔵 WHATSAPP 🔵
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - 🇮🇩 TRAFFIC INDO 🇮🇩
  url: http://www.gstatic.com/generate_204
  interval: '10'
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - 112.215.203.254
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 112.215.203.254
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,rule_direct,DIRECT
- RULE-SET,rule_reject,REJECT
- RULE-SET,rule_browsing,🟡 BROWSING 🟡
- RULE-SET,rule_streaming,🟠 STREAMING 🟠
- RULE-SET,rule_sosmed,🟢 SOSMED 🟢
- RULE-SET,rule_trafficindo,🇮🇩 TRAFFIC INDO 🇮🇩
- RULE-SET,rule_whatsapp,🔵 WHATSAPP 🔵
- RULE-SET,rule_adblock⛔ ADBLOCK ⛔
- MATCH,🟡 BROWSING 🟡
rule-providers:
  rule_direct:
    type: http
    behavior: classical
    path: "./GB_direct.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_direct.yaml
    interval: 86400
  rule_reject:
    type: http
    behavior: classical
    path: "./GB_reject.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_reject.yaml
    interval: 86400
  rule_browsing:
    type: http
    behavior: classical
    path: "./GB_browsing.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_browsing.yaml
    interval: 86400
  rule_streaming:
    type: http
    behavior: classical
    path: "./GB_streaming.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_streaming.yaml
    interval: 86400
  rule_sosmed:
    type: http
    behavior: classical
    path: "./GB_sosmed.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_sosmed.yaml
    interval: 86400
  rule_trafficindo:
    type: http
    behavior: classical
    path: "./GB_trafficindo.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_trafficindo.yaml
    interval: 86400    
  rule_whatsapp:
    type: http
    behavior: classical
    path: "./GB_whatsapp.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_whatsapp.yaml
    interval: 86400
  rule_adblock:
    type: http
    behavior: classical
    path: "./GB_adblock.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_rule/main/rule_provider/GB_adblock.yaml
    interval: 86400
